import { Language, Translations } from './types';

const COMMON_CONTACT = {
  address: 'San Pedro del Pinatar, Murcia, España', 
  phone: '+34 667 553 453',
  email: 'piedad.inter.easy@gmail.com'
};

export const TRANSLATIONS: Translations = {
  [Language.DE]: {
    welcome: 'Willkommen',
    welcomeConnector: 'bei',
    est: 'Gegr. 2024',
    tagline: 'Green Trade',
    enter: 'Eintreten',
    contactHeader: 'Kontakt',
    productsHeader: 'Unser Sortiment',
    viewProducts: 'Unsere Produkte ansehen',
    sectionFresh: 'Frisch',
    sectionFrozen: 'Tiefgekühlt',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Frische garantiert',
    heroDescription: 'Wir bringen den Garten vor Ihre Haustür. Professioneller Vertrieb für eine bunte Welt.',
    hq: 'Hauptsitz',
    getInTouch: 'Kontaktieren',
    rightsReserved: 'Alle Rechte vorbehalten.',
    moreVariety: 'Für mehr Auswahl, fragen Sie uns!',
    productNames: {
      redPepper: 'Rote Paprika',
      greenPepper: 'Grüne Paprika',
      yellowPepper: 'Gelbe Paprika',
      orangePepper: 'Orange Paprika',
      eggplant: 'Aubergine',
      zucchini: 'Zucchini',
      onion: 'Zwiebel',
      potato: 'Kartoffel',
      tomato: 'Tomate',
      broccoli: 'Brokkoli',
      cauliflower: 'Blumenkohl',
      cucumber: 'Gurke',
      celery: 'Sellerie',
      sweetPotato: 'Süßkartoffel',
      pumpkin: 'Kürbis',
      artichoke: 'Artischocke',
      leek: 'Lauch',
      fennel: 'Fenchel',
      carrot: 'Karotte',
      romanesco: 'Romanesco',
      chard: 'Mangold',
      lettuce: 'Salat',
    },
  },
  [Language.EN]: {
    welcome: 'Welcome',
    welcomeConnector: 'to',
    est: 'Est. 2024',
    tagline: 'Green Trade',
    enter: 'Enter Site',
    contactHeader: 'Contact',
    productsHeader: 'Our Collection',
    viewProducts: 'See our products',
    sectionFresh: 'Fresh',
    sectionFrozen: 'Frozen',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Freshness guaranteed',
    heroDescription: 'We bring the garden to your doorstep. Professional distribution for a colorful world.',
    hq: 'Headquarters',
    getInTouch: 'Get in touch',
    rightsReserved: 'All rights reserved.',
    moreVariety: 'For more variety, ask us!',
    productNames: {
      redPepper: 'Red Pepper',
      greenPepper: 'Green Pepper',
      yellowPepper: 'Yellow Pepper',
      orangePepper: 'Orange Pepper',
      eggplant: 'Eggplant',
      zucchini: 'Zucchini',
      onion: 'Onion',
      potato: 'Potato',
      tomato: 'Tomato',
      broccoli: 'Broccoli',
      cauliflower: 'Cauliflower',
      cucumber: 'Cucumber',
      celery: 'Celery',
      sweetPotato: 'Sweet Potato',
      pumpkin: 'Pumpkin',
      artichoke: 'Artichoke',
      leek: 'Leek',
      fennel: 'Fennel',
      carrot: 'Carrot',
      romanesco: 'Romanesco',
      chard: 'Chard',
      lettuce: 'Lettuce',
    },
  },
  [Language.FR]: {
    welcome: 'Bienvenue',
    welcomeConnector: 'chez',
    est: 'Est. 2024',
    tagline: 'Green Trade',
    enter: 'Entrer',
    contactHeader: 'Contact',
    productsHeader: 'Nos Produits',
    viewProducts: 'Voir nos produits',
    sectionFresh: 'Frais',
    sectionFrozen: 'Surgelés',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Fraîcheur garantie',
    heroDescription: 'Nous apportons le jardin à votre porte. Une distribution professionnelle pour un monde coloré.',
    hq: 'Siège social',
    getInTouch: 'Contactez-nous',
    rightsReserved: 'Tous droits réservés.',
    moreVariety: 'Pour plus de variété, demandez-nous !',
    productNames: {
      redPepper: 'Poivron Rouge',
      greenPepper: 'Poivron Vert',
      yellowPepper: 'Poivron Jaune',
      orangePepper: 'Poivron Orange',
      eggplant: 'Aubergine',
      zucchini: 'Courgette',
      onion: 'Oignon',
      potato: 'Pomme de Terre',
      tomato: 'Tomate',
      broccoli: 'Brocoli',
      cauliflower: 'Chou-fleur',
      cucumber: 'Concombre',
      celery: 'Céleri',
      sweetPotato: 'Patate Douce',
      pumpkin: 'Citrouille',
      artichoke: 'Artichaut',
      leek: 'Poireau',
      fennel: 'Fenouil',
      carrot: 'Carotte',
      romanesco: 'Romanesco',
      chard: 'Blette',
      lettuce: 'Laitue',
    },
  },
  [Language.ES]: {
    welcome: 'Bienvenido',
    welcomeConnector: 'a',
    est: 'Est. 2024',
    tagline: 'Green Trade',
    enter: 'Entrar',
    contactHeader: 'Contacto',
    productsHeader: 'Nuestra Selección',
    viewProducts: 'Ver nuestros productos',
    sectionFresh: 'Frescos',
    sectionFrozen: 'Congelados',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Frescura garantizada',
    heroDescription: 'Llevamos el jardín a tu puerta. Distribución profesional para un mundo lleno de color.',
    hq: 'Sede central',
    getInTouch: 'Contáctanos',
    rightsReserved: 'Todos los derechos reservados.',
    moreVariety: 'Para más variedad pregúntanos!',
    productNames: {
      redPepper: 'Pimiento Rojo',
      greenPepper: 'Pimiento Verde',
      yellowPepper: 'Pimiento Amarillo',
      orangePepper: 'Pimiento Naranja',
      eggplant: 'Berenjena',
      zucchini: 'Calabacín',
      onion: 'Cebolla',
      potato: 'Patata',
      tomato: 'Tomate',
      broccoli: 'Brócoli',
      cauliflower: 'Coliflor',
      cucumber: 'Pepino',
      celery: 'Apio',
      sweetPotato: 'Boniato',
      pumpkin: 'Calabaza',
      artichoke: 'Alcachofa',
      leek: 'Puerro',
      fennel: 'Hinojo',
      carrot: 'Zanahoria',
      romanesco: 'Romanesco',
      chard: 'Acelga',
      lettuce: 'Lechuga',
    },
  },
  [Language.IT]: {
    welcome: 'Benvenuto',
    welcomeConnector: 'in',
    est: 'Est. 2024',
    tagline: 'Green Trade',
    enter: 'Entra',
    contactHeader: 'Contatti',
    productsHeader: 'Prodotti',
    viewProducts: 'Vedi i nostri prodotti',
    sectionFresh: 'Freschi',
    sectionFrozen: 'Surgelati',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Freschezza garantita',
    heroDescription: 'Portiamo il giardino a casa tua. Distribuzione professionale per un mondo colorato.',
    hq: 'Sede centrale',
    getInTouch: 'Contattaci',
    rightsReserved: 'Tutti i diritti riservati.',
    moreVariety: 'Per una maggiore varietà, chiedici!',
    productNames: {
      redPepper: 'Peperone Rosso',
      greenPepper: 'Peperone Verde',
      yellowPepper: 'Peperone Giallo',
      orangePepper: 'Peperone Arancione',
      eggplant: 'Melanzana',
      zucchini: 'Zucchina',
      onion: 'Cipolla',
      potato: 'Patata',
      tomato: 'Pomodoro',
      broccoli: 'Broccolo',
      cauliflower: 'Cavolfiore',
      cucumber: 'Cetriolo',
      celery: 'Sedano',
      sweetPotato: 'Patata Dolce',
      pumpkin: 'Zucca',
      artichoke: 'Carciofo',
      leek: 'Porro',
      fennel: 'Finocchio',
      carrot: 'Carota',
      romanesco: 'Romanesco',
      chard: 'Bietola',
      lettuce: 'Lattuga',
    },
  },
  [Language.PT]: {
    welcome: 'Bem-vindo',
    welcomeConnector: 'à',
    est: 'Est. 2024',
    tagline: 'Green Trade',
    enter: 'Entrar',
    contactHeader: 'Contato',
    productsHeader: 'Produtos',
    viewProducts: 'Ver nossos produtos',
    sectionFresh: 'Frescos',
    sectionFrozen: 'Congelados',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Frescura garantida',
    heroDescription: 'Levamos o jardim até à sua porta. Distribuição profissional para um mundo colorido.',
    hq: 'Sede',
    getInTouch: 'Entre em contato',
    rightsReserved: 'Todos os direitos reservados.',
    moreVariety: 'Para mais variedade, pergunte-nos!',
    productNames: {
      redPepper: 'Pimento Vermelho',
      greenPepper: 'Pimento Verde',
      yellowPepper: 'Pimento Amarelo',
      orangePepper: 'Pimento Laranja',
      eggplant: 'Beringela',
      zucchini: 'Curgete',
      onion: 'Cebola',
      potato: 'Batata',
      tomato: 'Tomate',
      broccoli: 'Brócolos',
      cauliflower: 'Couve-flor',
      cucumber: 'Pepino',
      celery: 'Aipo',
      sweetPotato: 'Batata Doce',
      pumpkin: 'Abóbora',
      artichoke: 'Alcachofra',
      leek: 'Alho-porro',
      fennel: 'Funcho',
      carrot: 'Cenoura',
      romanesco: 'Romanesco',
      chard: 'Acelga',
      lettuce: 'Alface',
    },
  },
};