import { Language, Translations } from './types';

const COMMON_CONTACT = {
  address: 'San Pedro del Pinatar, Murcia, España', 
  phone: '+34 667 553 453',
  email: 'piedad.inter.easy@gmail.com'
};

export const TRANSLATIONS: Translations = {
  [Language.DE]: {
    welcome: 'Willkommen',
    welcomeConnector: 'bei',
    est: 'Gegr. 2024',
    tagline: 'Green Traders',
    enter: 'Eintreten',
    contactHeader: 'Kontakt',
    productsHeader: 'Unser Sortiment',
    viewProducts: 'Unsere Produkte ansehen',
    backToHome: 'Zurück zur Startseite',
    saveContact: 'Kontakt speichern',
    sectionFresh: 'Frisch',
    sectionFrozen: 'Tiefgekühlt',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Frische garantiert',
    heroDescription: 'Willkommen bei InterEasy! Wir bringen den Gemüsegarten Europas zu Ihnen. Als Handelsvertreter verbinden wir Erzeuger mit Käufern und Fabriken durch professionelle Vermittlung.',
    availabilityNotice: 'Die Verfügbarkeit der Produkte kann sich je nach saisonaler Ernte und Wetterbedingungen ändern.',
    hq: 'Hauptsitz',
    getInTouch: 'Kontaktieren',
    rightsReserved: 'Alle Rechte vorbehalten.',
    moreVariety: 'Für mehr Auswahl, fragen Sie uns!',
    productNames: {
      redPepper: 'Rote Paprika',
      greenPepper: 'Grüne Paprika',
      yellowPepper: 'Gelbe Paprika',
      orangePepper: 'Orange Paprika',
      eggplant: 'Aubergine',
      zucchini: 'Zucchini',
      onion: 'Zwiebel',
      potato: 'Kartoffel',
      tomato: 'Tomate',
      broccoli: 'Brokkoli',
      cauliflower: 'Blumenkohl',
      cucumber: 'Gurke',
      celery: 'Sellerie',
      sweetPotato: 'Süßkartoffel',
      pumpkin: 'Kürbis',
      artichoke: 'Artischocke',
      leek: 'Lauch',
      fennel: 'Fenchel',
      carrot: 'Karotte',
      romanesco: 'Romanesco',
      chard: 'Mangold',
      lettuce: 'Salat',
      beetroot: 'Rote Bete',
      kale: 'Grünkohl',
      cabbages: 'Kohl',
      spinach: 'Spinat',
      corn: 'Mais',
      daikon: 'Rettich',
      parsnip: 'Pastinake',
    },
  },
  [Language.EN]: {
    welcome: 'Welcome',
    welcomeConnector: 'to',
    est: 'Est. 2024',
    tagline: 'Green Traders',
    enter: 'Enter Site',
    contactHeader: 'Contact',
    productsHeader: 'Our Collection',
    viewProducts: 'See our products',
    backToHome: 'Back to Home',
    saveContact: 'Save Contact',
    sectionFresh: 'Fresh',
    sectionFrozen: 'Frozen',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Freshness guaranteed',
    heroDescription: 'Welcome to InterEasy! We bridge the gap between Europe\'s orchard and your business. As commercial agents, we link producers with buyers and factories through strategic brokerage.',
    availabilityNotice: 'Product availability is subject to change based on seasonal harvest and weather conditions.',
    hq: 'Headquarters',
    getInTouch: 'Get in touch',
    rightsReserved: 'All rights reserved.',
    moreVariety: 'For more variety, ask us!',
    productNames: {
      redPepper: 'Red Pepper',
      greenPepper: 'Green Pepper',
      yellowPepper: 'Yellow Pepper',
      orangePepper: 'Orange Pepper',
      eggplant: 'Aubergine',
      zucchini: 'Zucchini',
      onion: 'Onion',
      potato: 'Potato',
      tomato: 'Tomato',
      broccoli: 'Broccoli',
      cauliflower: 'Cauliflower',
      cucumber: 'Cucumber',
      celery: 'Celery',
      sweetPotato: 'Sweet Potato',
      pumpkin: 'Butternut Squash',
      artichoke: 'Artichoke',
      leek: 'Leek',
      fennel: 'Fennel',
      carrot: 'Carrot',
      romanesco: 'Romanesco',
      chard: 'Chard',
      lettuce: 'Lettuce',
      beetroot: 'Beetroot',
      kale: 'Kale',
      cabbages: 'Cabbages',
      spinach: 'Spinach',
      corn: 'Corn',
      daikon: 'Daikon',
      parsnip: 'Parsnip',
    },
  },
  [Language.ES]: {
    welcome: 'Bienvenido',
    welcomeConnector: 'a',
    est: 'Est. 2024',
    tagline: 'Green Traders',
    enter: 'Entrar',
    contactHeader: 'Contacto',
    productsHeader: 'Nuestra Selección',
    viewProducts: 'Ver nuestros productos',
    backToHome: 'Volver al Inicio',
    saveContact: 'Guardar contacto',
    sectionFresh: 'Frescos',
    sectionFrozen: 'Congelados',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Frescura garantizada',
    heroDescription: '¡Bienvenido a InterEasy! Acercamos la huerta de Europa a ti. Como agente comercial, soy el enlace estratégico entre productores, compradores y fábricas.',
    availabilityNotice: 'La disponibilidad de los productos está sujeta a cambios según la cosecha estacional y las condiciones climáticas.',
    hq: 'Sede central',
    getInTouch: 'Contáctanos',
    rightsReserved: 'Todos los derechos reservados.',
    moreVariety: '¡Para más variedad pregúntanos!',
    productNames: {
      redPepper: 'Pimiento Rojo',
      greenPepper: 'Pimiento Verde',
      yellowPepper: 'Pimiento Amarillo',
      orangePepper: 'Pimiento Naranja',
      eggplant: 'Berenjena',
      zucchini: 'Calabacín',
      onion: 'Cebolla',
      potato: 'Patata',
      tomato: 'Tomate',
      broccoli: 'Brócoli',
      cauliflower: 'Coliflor',
      cucumber: 'Pepino',
      celery: 'Apio',
      sweetPotato: 'Boniato',
      pumpkin: 'Calabaza',
      artichoke: 'Alcachofa',
      leek: 'Puerro',
      fennel: 'Hinojo',
      carrot: 'Zanahoria',
      romanesco: 'Romanesco',
      chard: 'Acelga',
      lettuce: 'Lechuga',
      beetroot: 'Remolacha',
      kale: 'Col Rizada',
      cabbages: 'Coles',
      spinach: 'Espinacas',
      corn: 'Maíz',
      daikon: 'Rábano Daikon',
      parsnip: 'Chirivía',
    },
  },
  [Language.FR]: {
    welcome: 'Bienvenue',
    welcomeConnector: 'chez',
    est: 'Est. 2024',
    tagline: 'Green Traders',
    enter: 'Entrer',
    contactHeader: 'Contact',
    productsHeader: 'Nos Produits',
    viewProducts: 'Voir nos produits',
    backToHome: 'Retour à l\'accueil',
    saveContact: 'Enregistrer le contact',
    sectionFresh: 'Frais',
    sectionFrozen: 'Surgelés',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Fraîcheur garantie',
    heroDescription: 'Bienvenue chez InterEasy ! Nous vous apportons le potager de l\'Europe. En tant qu\'agents commerciaux, nous connectons les producteurs aux acheteurs et aux usines par une intermédiation professionnelle.',
    availabilityNotice: 'La disponibilité des produits est sujette à changement en fonction de la récolte saisonnière et des conditions météorologiques.',
    hq: 'Siège social',
    getInTouch: 'Contactez-nous',
    rightsReserved: 'Tous droits réservés.',
    moreVariety: 'Pour plus de variété, demandez-nous !',
    productNames: {
      redPepper: 'Poivron Rouge',
      greenPepper: 'Poivron Vert',
      yellowPepper: 'Poivron Jaune',
      orangePepper: 'Poivron Orange',
      eggplant: 'Aubergine',
      zucchini: 'Courgette',
      onion: 'Oignon',
      potato: 'Pomme de Terre',
      tomato: 'Tomate',
      broccoli: 'Brocoli',
      cauliflower: 'Chou-fleur',
      cucumber: 'Concombre',
      celery: 'Céleri',
      sweetPotato: 'Patate Douce',
      pumpkin: 'Citrouille',
      artichoke: 'Artichaut',
      leek: 'Poireau',
      fennel: 'Fenouil',
      carrot: 'Carotte',
      romanesco: 'Romanesco',
      chard: 'Blette',
      lettuce: 'Laitue',
      beetroot: 'Betterave',
      kale: 'Chou frisé',
      cabbages: 'Choux',
      spinach: 'Épinards',
      corn: 'Maïs',
      daikon: 'Daikon',
      parsnip: 'Panais',
    },
  },
  [Language.IT]: {
    welcome: 'Benvenuto',
    welcomeConnector: 'in',
    est: 'Est. 2024',
    tagline: 'Green Traders',
    enter: 'Entra',
    contactHeader: 'Contatti',
    productsHeader: 'Prodotti',
    viewProducts: 'Vedi i nostri prodotti',
    backToHome: 'Torna alla Home',
    saveContact: 'Salva contatto',
    sectionFresh: 'Freschi',
    sectionFrozen: 'Surgelati',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Freschezza garantita',
    heroDescription: 'Benvenuti in InterEasy! Portiamo l\'orto d\'Europa da te. Come agenti commerciali, colleghiamo produttori con acquirenti e fabbriche attraverso un\'intermediazione strategica e professionale.',
    availabilityNotice: 'La disponibilità dei prodotti è soggetta a variazioni in base al raccolto stagionale e alle condizioni meteorologiche.',
    hq: 'Sede centrale',
    getInTouch: 'Contattaci',
    rightsReserved: 'Tutti i diritti riservati.',
    moreVariety: 'Per una maggiore varietà, chiedici!',
    productNames: {
      redPepper: 'Peperone Rosso',
      greenPepper: 'Peperone Verde',
      yellowPepper: 'Peperone Giallo',
      orangePepper: 'Peperone Arancione',
      eggplant: 'Melanzana',
      zucchini: 'Zucchina',
      onion: 'Cipolla',
      potato: 'Patata',
      tomato: 'Pomodoro',
      broccoli: 'Broccolo',
      cauliflower: 'Cavolfiore',
      cucumber: 'Cetriolo',
      celery: 'Sedano',
      sweetPotato: 'Patata Dolce',
      pumpkin: 'Zucca',
      artichoke: 'Carciofo',
      leek: 'Porro',
      fennel: 'Finocchio',
      carrot: 'Carota',
      romanesco: 'Romanesco',
      chard: 'Bietola',
      lettuce: 'Lattuga',
      beetroot: 'Barbabietola',
      kale: 'Cavolo riccio',
      cabbages: 'Cavoli',
      spinach: 'Spinaci',
      corn: 'Mais',
      daikon: 'Daikon',
      parsnip: 'Pastinaca',
    },
  },
  [Language.PT]: {
    welcome: 'Bem-vindo',
    welcomeConnector: 'à',
    est: 'Est. 2024',
    tagline: 'Green Traders',
    enter: 'Entrar',
    contactHeader: 'Contato',
    productsHeader: 'Produtos',
    viewProducts: 'Ver nossos produtos',
    backToHome: 'Voltar ao Início',
    saveContact: 'Salvar contato',
    sectionFresh: 'Frescos',
    sectionFrozen: 'Congelados',
    address: COMMON_CONTACT.address,
    phone: COMMON_CONTACT.phone,
    email: COMMON_CONTACT.email,
    freshnessGuaranteed: 'Frescura garantida',
    heroDescription: 'Bem-vindo à InterEasy! Trazemos a horta da Europa até si. Como agentes comerciais, ligamos produtores a compradores e fábricas através de uma intermediação estratégica e profissional.',
    availabilityNotice: 'A disponibilidade do produto está sujeita a alterações com base na colheita sazonal e nas condições meteorológicas.',
    hq: 'Sede',
    getInTouch: 'Entre em contato',
    rightsReserved: 'Todos os derechos reservados.',
    moreVariety: 'Para mais variedade, pergunte-nos!',
    productNames: {
      redPepper: 'Pimento Vermelho',
      greenPepper: 'Pimento Verde',
      yellowPepper: 'Pimento Amarelo',
      orangePepper: 'Pimento Laranja',
      eggplant: 'Beringela',
      zucchini: 'Curgete',
      onion: 'Cebola',
      potato: 'Batata',
      tomato: 'Tomate',
      broccoli: 'Brócolos',
      cauliflower: 'Couve-flor',
      cucumber: 'Pepino',
      celery: 'Aipo',
      sweetPotato: 'Batata Doce',
      pumpkin: 'Abóbora',
      artichoke: 'Alcachofra',
      leek: 'Alho-porro',
      fennel: 'Funcho',
      carrot: 'Cenoura',
      romanesco: 'Romanesco',
      chard: 'Acelga',
      lettuce: 'Alface',
      beetroot: 'Beterraba',
      kale: 'Couve-galega',
      cabbages: 'Couves',
      spinach: 'Espinafre',
      corn: 'Milho',
      daikon: 'Rabanete Daikon',
      parsnip: 'Chirivia',
    },
  },
};